Name = "Light Block"
Category = "Prop"
Version = 1
Notes = "Actor ported from Majora's Mask, block that dissolves when shot by a light arrow. The special effect requires object 00A8 in the room."
[[Render]]
    Regex = "...."
    Segment = 6
    Scale = 0.5
    ScaleMask = 0x0001
    ScaleTarget = "Var"
    ScaleArray = [ 0.1,0.16666]
    DisplayList = "0x06000178"
[[Property]]
    Mask          = 0x0001
    Name          = "Type"
    Target        = "Var"
    Dropdown = [ [ 0, "Normal"],[ 1, "Big"]]
[[Property]]
	Mask          = 0x3F00
	Name          = "Switch Flag"
	Target        = "Var"